# USE SAME DB IN DEV AND PRODUCTION

# nb no production db yet

development:
  adapter: postgresql
  encoding: utf8
  database: news_development
  pool: 5
  username: lemez
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: news_test
  pool: 5
  username: lemez
  password:
